### ISSUE TITLE
Home Assistant 2022.2.5 + HACS-mopidy 1.4.3

### ISSUE THREAD

**Issue by jeliss** [bushvin/hass-integrations#15]
Upon startup receiving error:

```
2022-02-11 15:46:53 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 185, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 183, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/mopidy/config_flow.py", line 136, in async_step_zeroconf
    getattr(discovery_info, CONF_NAME)[: len(getattr(discovery_info, CONF_TYPE) +1) * -1]
TypeError: can only concatenate str (not "int") to str
````
Using the UI integration if that matters...

**Comment by bushvin** [comment]
Duplicate of secondary issue in #13

Would you mind testing my newest code?

**Comment by jeliss** [comment]
Pull #14 fixed.  Thanks!

**Comment by bushvin** [comment]
New release published
