### ISSUE TITLE
Errors on HA startup in beta 2021.4x

### ISSUE THREAD

**Issue by VDRainer** [bushvin/hass-integrations#4]
On HA 2021.4.x beta seeing multiple errors on startup.
The Integration works without issues, just for info.
```
2021-04-04 10:57:26 ERROR (SyncWorker_1) [mopidyapi.client] Could not decode json from Mopidy: Expecting value: line 1 column 1 (char 0)
--- Logging error ---
Traceback (most recent call last):
  File "/srv/ha/lib/python3.8/site-packages/mopidyapi/client.py", line 77, in rpc_call
    r = post(self.http_url,
  File "/srv/ha/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassi/.homeassistant/custom_components/mopidy/config_flow.py", line 102, in async_step_zeroconf
    await self.hass.async_add_executor_job(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassi/.homeassistant/custom_components/mopidy/config_flow.py", line 24, in _validate_input
    client.rpc_call("core.get_version")
  File "/srv/ha/lib/python3.8/site-packages/mopidyapi/client.py", line 100, in rpc_call
    raise ConnectionError(ex)
requests.exceptions.ConnectionError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 1401, in emit
    self.enqueue(self.prepare(record))
  File "/usr/lib/python3.8/logging/handlers.py", line 1384, in prepare
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/srv/ha/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/srv/ha/lib/python3.8/site-packages/homeassistant/__main__.py", line 313, in main
    exit_code = runner.run(runtime_conf)
  File "/srv/ha/lib/python3.8/site-packages/homeassistant/runner.py", line 113, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/homeassi/.homeassistant/custom_components/mopidy/config_flow.py", line 106, in async_step_zeroconf
    _LOGGER.warning("Not a mopidy server", error)
  File "/usr/lib/python3.8/logging/__init__.py", line 1454, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/srv/ha/lib/python3.8/site-packages/homeassistant/util/logging.py", line 50, in handle
    self.emit(record)
Message: 'Not a mopidy server'
Arguments: (ConnectionError(JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),)
```

**Comment by bushvin** [comment]
This happens when another http zerconf device is found.
the component tries to connect, but fails, throwing this error.
I'll see if I can turn it down a notch

**Comment by bushvin** [comment]
@VDRainer 
I believe I may have found the culprit for the overload in feedback.
I hope to have it fixed in my latest commit (a17d76875c442faf0cfb22d6e34aad5e5f6ec085)
Could you provide some feedback when you have time to try?

**Comment by VDRainer** [comment]
@bushvin , thanks for looking at this and your great integration.
Here's the log after first restart.
```
2021-04-05 22:27:26 ERROR (SyncWorker_19) [mopidyapi.client] Could not decode json from Mopidy: Expecting value: line 1 column 1 (char 0)
2021-04-05 22:27:26 ERROR (SyncWorker_3) [mopidyapi.client] Could not decode json from Mopidy: Expecting value: line 1 column 1 (char 0)
2021-04-05 22:27:27 ERROR (SyncWorker_3) [mopidyapi.client] Could not decode json from Mopidy: Expecting value: line 1 column 1 (char 0)
2021-04-05 22:27:27 ERROR (SyncWorker_2) [mopidyapi.client] Could not decode json from Mopidy: Expecting value: line 1 column 1 (char 0)
2021-04-05 22:27:27 ERROR (SyncWorker_11) [mopidyapi.client] Could not decode json from Mopidy: Expecting value: line 1 column 1 (char 0)
2021-04-05 22:27:27 WARNING (MainThread) [custom_components.mopidy.config_flow] NAS01.local.@5000 is not a mopidy server
2021-04-05 22:27:27 WARNING (MainThread) [custom_components.mopidy.config_flow] OSMC3.local.@8080 is not a mopidy server
2021-04-05 22:27:27 ERROR (SyncWorker_21) [mopidyapi.client] Could not decode json from Mopidy: Expecting value: line 1 column 1 (char 0)
2021-04-05 22:27:27 WARNING (MainThread) [custom_components.mopidy.config_flow] sonoff16apow01-2494.local.@80 is not a mopidy server
2021-04-05 22:27:27 WARNING (MainThread) [custom_components.mopidy.config_flow] milight-hub.local.@80 is not a mopidy server
2021-04-05 22:27:27 WARNING (MainThread) [custom_components.mopidy.config_flow] sonoff16a-7105.local.@80 is not a mopidy server
2021-04-05 22:27:27 WARNING (MainThread) [custom_components.mopidy.config_flow] 4C268D000000.local.@80 is not a mopidy server
```

**Comment by bushvin** [comment]
This behaviour is consistent with the initial mopidy connection.
Unfortunately, the mopidy module doesn't have a decent way to detect if a device is a mopidy server or not.
might include this in a future release of the integration...

**Comment by guix77** [comment]
Hi,

I have a way to fix this, so I'm reopening to reference it from my PR.
