### ISSUE TITLE
Error log after update to 2.3.0

### ISSUE THREAD

**Issue by paszczaq** [bushvin/hass-integrations#64]
Hi, after update to 2.3.0 I'm getting error in log:

Did reinstall and restar Home Assistant

Anyone seeing same behavior?

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:894
First occurred: 12:34:45 (75 occurrences)
Last logged: 12:47:05

Update for media_player.radio fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 894, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1214, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mopidy/media_player.py", line 607, in update
    self.speaker.update()
  File "/config/custom_components/mopidy/speaker.py", line 973, in update
    self.queue.update()
  File "/config/custom_components/mopidy/speaker.py", line 311, in update
    self.update_current_track()
  File "/config/custom_components/mopidy/speaker.py", line 330, in update_current_track
    self.update_current_image_url()
  File "/config/custom_components/mopidy/speaker.py", line 343, in update_current_image_url
    self._current_track_image_url = self.__get_track_image(uri)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mopidy/speaker.py", line 191, in __get_track_image
    elif (self.queue[tlid].get("is_stream")):
                     ^^^^
NameError: name 'tlid' is not defined

```

**Comment by bushvin** [comment]
Apologies, should be fixed with 6d4afc2b143eb04e78989357a3f91f46057f4eb0

Will draft a new version momentarily
