### ISSUE TITLE
mopidy mediaplayer not working

### ISSUE THREAD

**Issue by WilcoKakkenberg** [bushvin/hass-integrations#66]
log entry:

Logger: homeassistant.setup
Source: setup.py:403
First occurred: 11:04:55 (1 occurrences)
Last logged: 11:04:55

Unable to prepare setup for platform 'mopidy.media_player': Platform not found (Exception importing custom_components.mopidy.media_player).

Home Assistant

Core                       2024.1.3
Supervisor             2023.12.1
Operating System 11.4
Frontend               20240104.0

Logger:

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 11:04:55 (1 occurrences)
Last logged: 11:04:55

Unexpected exception importing platform custom_components.mopidy.media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/mopidy/media_player.py", line 161, in <module>
    class MopidyMediaPlayerEntity(MediaPlayerEntity):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_supported_features in subclass

**Comment by bushvin** [comment]
Could you please check that you have a `custom_components/mopidy` directory in the `config` directory of your Home Assistant instance?

Would it be possible to provide me with the output of
```bash
find /config/custom_components/mopidy -type f -exec ls -la {} +
```

thank you

**Comment by WilcoKakkenberg** [comment]
thnx for your quick response.

see attached:
![image](https://github.com/bushvin/hass-integrations/assets/48676067/4237c695-b0ed-4d84-bf0a-da94ded0dc30)

**Comment by bushvin** [comment]
I have absolutely no idea what is causing this...
Are you sure you are running the latest version of the integration?

can you post the results of:
```shell
cat /config/custom_components/mopidy/manifest.json```
?
the version should be 2.3+

**Comment by WilcoKakkenberg** [comment]
Installed version 2.3.3 tonight .

Entities are visible again in HA.

Will test player function tomorrow.

Thnx for the quick fix!!
